language: python

python:
    - 2.7
    - 3.3

env:
    - NUMPY_VERSION=1.8 ASTROPY_VERSION=0.3.1

before_install:
   - source .setup_conda.sh $TRAVIS_PYTHON_VERSION
   - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda3/bin:$PATH

install:
   - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION astropy=$ASTROPY_VERSION scipy pytest pip
   - pip install pytest-cov coveralls

script:
   - py.test --cov pvextractor

after_success:
 - coveralls